import type { ActionDefinition } from "@/game/types";

export const actionDefinitions: ActionDefinition[] = [
  {
    type: "smart_ev",
    label: "Recharge EV intelligente",
    shortLabel: "EV smart",
    target: "Bornes EV",
    description: "Lisse la recharge des véhicules pendant 80 minutes.",
    expectedImpact: "Baisse le pic immédiat, avec une légère friction publique.",
    commandCost: 10,
    cooldownMinutes: 35,
    defaultDurationMinutes: 80,
    defaultIntensityMw: 24,
  },
  {
    type: "defer_ai",
    label: "Décaler job IA",
    shortLabel: "Décaler IA",
    target: "Job IA flexible",
    description: "Reporte le job IA flexible le plus lourd hors du pic.",
    expectedImpact: "Réduit la demande sans couper les services critiques.",
    commandCost: 15,
    cooldownMinutes: 25,
    defaultDurationMinutes: 75,
  },
  {
    type: "migrate_ai",
    label: "Migrer workload IA",
    shortLabel: "Migration",
    target: "Datacenter IA",
    description: "Déplace un job IA flexible vers un datacenter moins congestionné.",
    expectedImpact: "Soulage la zone locale, mais ajoute une petite friction opérationnelle.",
    commandCost: 18,
    cooldownMinutes: 35,
    defaultDurationMinutes: 45,
  },
  {
    type: "externalize_ai",
    label: "Cloud externe",
    shortLabel: "Cloud ext.",
    target: "Job IA non souverain",
    description: "Bascule un job actif non critique hors du réseau local.",
    expectedImpact: "Soulage immédiatement la charge, mais pénalise souveraineté et coût.",
    commandCost: 8,
    cooldownMinutes: 55,
    defaultDurationMinutes: 90,
  },
  {
    type: "reduce_model",
    label: "Réduire modèle IA",
    shortLabel: "Modèle -",
    target: "Job IA actif",
    description: "Passe un job non critique sur un modèle plus léger.",
    expectedImpact: "Baisse la puissance et le coût, avec une petite perte de qualité.",
    commandCost: 12,
    cooldownMinutes: 25,
    defaultDurationMinutes: 60,
  },
  {
    type: "activate_cache",
    label: "Activer cache IA",
    shortLabel: "Cache IA",
    target: "Datacenter IA",
    description: "Supprime une partie des appels redondants.",
    expectedImpact: "Très efficace sur les assistants et agents répétitifs.",
    commandCost: 10,
    cooldownMinutes: 50,
    defaultDurationMinutes: 120,
  },
  {
    type: "agent_timeout",
    label: "Timeout agent",
    shortLabel: "Timeout",
    target: "Agent IA",
    description: "Stoppe les boucles d'itérations sans valeur.",
    expectedImpact: "Coupe le gaspillage sans toucher aux jobs critiques.",
    commandCost: 8,
    cooldownMinutes: 20,
    defaultDurationMinutes: 40,
  },
  {
    type: "discharge_battery",
    label: "Décharger batterie",
    shortLabel: "Batterie",
    target: "Batteries réseau",
    description: "Injecte de la puissance stockée pendant 20 minutes.",
    expectedImpact: "Remonte vite la stabilité mais consomme la réserve.",
    commandCost: 20,
    cooldownMinutes: 30,
    defaultDurationMinutes: 20,
    defaultIntensityMw: 32,
  },
  {
    type: "import_energy",
    label: "Importer énergie",
    shortLabel: "Import",
    target: "Interconnexion",
    description: "Achète de l'énergie externe pendant 30 minutes.",
    expectedImpact: "Sécurise le réseau, mais pénalise coût et souveraineté.",
    commandCost: 0,
    cooldownMinutes: 35,
    defaultDurationMinutes: 30,
    defaultIntensityMw: 34,
  },
  {
    type: "thermal_backup",
    label: "Thermique secours",
    shortLabel: "Thermique",
    target: "Centrale secours",
    description: "Lance une production pilotable fortement carbonée.",
    expectedImpact: "Solution de dernier recours, très efficace mais très pénalisée.",
    commandCost: 0,
    cooldownMinutes: 35,
    defaultDurationMinutes: 25,
    defaultIntensityMw: 34,
  },
  {
    type: "curtail_industry",
    label: "Effacer industrie",
    shortLabel: "Effacement",
    target: "Site industriel",
    description: "Négocie une réduction temporaire de charge industrielle.",
    expectedImpact: "Soulage fortement le couloir Rhône, avec un coût économique.",
    commandCost: 16,
    cooldownMinutes: 40,
    defaultDurationMinutes: 30,
    defaultIntensityMw: 18,
  },
  {
    type: "reroute_line",
    label: "Rerouter ligne",
    shortLabel: "Reroute",
    target: "Ligne pilotable",
    description: "Ouvre temporairement une ligne surchargée pour redistribuer les flux.",
    expectedImpact: "Peut éteindre une alarme locale, mais surcharge parfois un voisin.",
    commandCost: 15,
    cooldownMinutes: 25,
    defaultDurationMinutes: 15,
  },
  {
    type: "repair_line",
    label: "Équipe réparation",
    shortLabel: "Réparer",
    target: "Ligne déclenchée",
    description: "Envoie une équipe pour remettre une ligne coupée en service.",
    expectedImpact: "Rétablit un corridor critique après un délai court.",
    commandCost: 18,
    cooldownMinutes: 45,
    defaultDurationMinutes: 5,
  },
  {
    type: "authorize_overload",
    label: "Surcharge temporaire",
    shortLabel: "Surcharge +",
    target: "Ligne critique",
    description: "Autorise une limite thermique plus haute pendant quelques minutes.",
    expectedImpact: "Achète du temps au prix d'un risque de déclenchement.",
    commandCost: 12,
    cooldownMinutes: 30,
    defaultDurationMinutes: 15,
  },
];

export function getActionDefinition(type: ActionDefinition["type"]) {
  return actionDefinitions.find((action) => action.type === type);
}
