const ACCENT_REPLACEMENTS: Array<[RegExp, string]> = [
  [/\bATHENA\b/g, "Athéna"],
  [/\bAthena\b/g, "Athéna"],
  [/\bdetecte\b/gi, "détecte"],
  [/\bdetection\b/gi, "détection"],
  [/\breseau\b/gi, "réseau"],
  [/\breseaux\b/gi, "réseaux"],
  [/\bsecurise\b/gi, "sécurisé"],
  [/\bsecuriser\b/gi, "sécuriser"],
  [/\bsecurisee\b/gi, "sécurisée"],
  [/\bstabilite\b/gi, "stabilité"],
  [/\bflexibilite\b/gi, "flexibilité"],
  [/\bflexibilites\b/gi, "flexibilités"],
  [/\bcapacite\b/gi, "capacité"],
  [/\bcapacites\b/gi, "capacités"],
  [/\bdepensee\b/gi, "dépensée"],
  [/\benergie\b/gi, "énergie"],
  [/\benergies\b/gi, "énergies"],
  [/\bciblee\b/gi, "ciblée"],
  [/\bciblees\b/gi, "ciblées"],
  [/\bdecharger\b/gi, "décharger"],
  [/\bdecharge\b/gi, "décharge"],
  [/\bdechargee\b/gi, "déchargée"],
  [/\bdecale\b/gi, "décale"],
  [/\bdecaler\b/gi, "décaler"],
  [/\bdeplace\b/gi, "déplace"],
  [/\breporte\b/gi, "reporté"],
  [/\breportee\b/gi, "reportée"],
  [/\breporter\b/gi, "reporter"],
  [/\bdemarre\b/gi, "démarre"],
  [/\bdemarrent\b/gi, "démarrent"],
  [/\breduire\b/gi, "réduire"],
  [/\breduit\b/gi, "réduit"],
  [/\breduira\b/gi, "réduira"],
  [/\breduisant\b/gi, "réduisant"],
  [/\breduction\b/gi, "réduction"],
  [/\bmodele\b/gi, "modèle"],
  [/\bmodeles\b/gi, "modèles"],
  [/\boptimise\b/gi, "optimisé"],
  [/\boptimisee\b/gi, "optimisée"],
  [/\boptimises\b/gi, "optimisés"],
  [/\bleger\b/gi, "léger"],
  [/\blegere\b/gi, "légère"],
  [/\bqualite\b/gi, "qualité"],
  [/\bvehicules\b/gi, "véhicules"],
  [/\bpenalise\b/gi, "pénalise"],
  [/\bpenalises\b/gi, "pénalisés"],
  [/\bpenaliser\b/gi, "pénaliser"],
  [/\bsouverainete\b/gi, "souveraineté"],
  [/\bdeja\b/gi, "déjà"],
  [/\bplutot\b/gi, "plutôt"],
  [/\btres\b/gi, "très"],
  [/\brisquee\b/gi, "risquée"],
  [/\brepetes\b/gi, "répétés"],
  [/\breduits\b/gi, "réduits"],
  [/\breviter\b/gi, "éviter"],
  [/\beviter\b/gi, "éviter"],
  [/\bequipe\b/gi, "équipe"],
  [/\breparation\b/gi, "réparation"],
  [/\bretablit\b/gi, "rétablit"],
  [/\blissee\b/gi, "lissée"],
  [/\bstoppee\b/gi, "stoppée"],
  [/\biterations\b/gi, "itérations"],
  [/\bdeclenchee\b/gi, "déclenchée"],
  [/\bdeclenchement\b/gi, "déclenchement"],
  [/\bpreparez\b/gi, "préparez"],
  [/\boperationnelle\b/gi, "opérationnelle"],
  [/\boperationnel\b/gi, "opérationnel"],
  [/\bimmediat\b/gi, "immédiat"],
  [/\bimmediate\b/gi, "immédiate"],
  [/\bimmediatement\b/gi, "immédiatement"],
  [/\bgerable\b/gi, "gérable"],
  [/\bdegrader\b/gi, "dégrader"],
  [/\bpreferable\b/gi, "préférable"],
  [/\bnumerique\b/gi, "numérique"],
  [/\bproteges\b/gi, "protégés"],
  [/\bprotegee\b/gi, "protégée"],
  [/\bprotege\b/gi, "protège"],
  [/\bestimee\b/gi, "estimée"],
  [/\bprevu\b/gi, "prévu"],
  [/\bmission terminee\b/gi, "mission terminée"],
  [/\bterminee\b/gi, "terminée"],
  [/\btermines\b/gi, "terminés"],
  [/\brefusee\b/gi, "refusée"],
  [/\bindisponibilite\b/gi, "indisponibilité"],
  [/\bcout\b/gi, "coût"],
  [/\bcouts\b/gi, "coûts"],
  [/\bCO2\b/g, "CO₂"],
];

function applyCase(match: string, replacement: string) {
  if (replacement === "Athéna") return replacement;
  if (match.toLocaleUpperCase("fr-FR") === match) return replacement.toLocaleUpperCase("fr-FR");
  if (match[0]?.toLocaleUpperCase("fr-FR") === match[0]) {
    return `${replacement[0]?.toLocaleUpperCase("fr-FR") ?? ""}${replacement.slice(1)}`;
  }
  return replacement;
}

export function restoreFrenchSpeechAccents(text: string) {
  return ACCENT_REPLACEMENTS.reduce(
    (next, [pattern, replacement]) => next.replace(pattern, (match) => applyCase(match, replacement)),
    text,
  );
}
