import type { Scenario } from "@/game/types";

export const eveningPeakScenario: Scenario = {
  id: "evening-peak",
  name: "Le pic de 19h",
  subtitle:
    "Gerez une fin de journee sous tension pendant que le datacenter IA lance ses jobs critiques.",
  startMinute: 17 * 60 + 30,
  endMinute: 20 * 60 + 30,
  tickMinutes: 5,
  objectives: [
    "Maintenir la stabilite reseau au-dessus de 50.",
    "Preserver l'hopital et le job cyber critique.",
    "Optimiser les charges IA flexibles sans couper l'IA utile.",
    "Eviter le thermique sauf urgence.",
  ],
  initialMetrics: {
    stability: 85,
    carbon: 86,
    cost: 78,
    sovereignty: 90,
    aiProductivity: 60,
    publicSatisfaction: 80,
    criticalContinuity: 100,
    batteryLevel: 65,
    productionMw: 172,
    demandMw: 161,
    aiLoadMw: 21,
    reserveMw: 11,
    co2Intensity: 44,
    score: 735,
  },
  assets: [
    {
      id: "nuclear",
      name: "Socle nucleaire",
      kind: "production",
      category: "nuclear",
      position: { x: 16, y: 28 },
      powerMw: 96,
      maxPowerMw: 96,
      status: "stable",
      critical: false,
      flexible: false,
      description: "Production bas carbone stable mais peu flexible a court terme.",
    },
    {
      id: "solar",
      name: "Parc solaire",
      kind: "production",
      category: "solar",
      position: { x: 32, y: 18 },
      powerMw: 28,
      maxPowerMw: 34,
      status: "watch",
      critical: false,
      flexible: false,
      description: "Production utile en journee, en baisse rapide avant le pic du soir.",
    },
    {
      id: "wind",
      name: "Eolien Atlantique",
      kind: "production",
      category: "wind",
      position: { x: 17, y: 72 },
      powerMw: 20,
      maxPowerMw: 34,
      status: "stable",
      critical: false,
      flexible: false,
      description: "Production variable avec incertitude meteo.",
    },
    {
      id: "hydro",
      name: "Hydraulique reserve",
      kind: "production",
      category: "hydro",
      position: { x: 34, y: 82 },
      powerMw: 26,
      maxPowerMw: 34,
      status: "stable",
      critical: false,
      flexible: true,
      description: "Reserve pilotable gardee pour absorber les pointes.",
    },
    {
      id: "battery",
      name: "Batteries reseau",
      kind: "storage",
      category: "battery",
      position: { x: 50, y: 28 },
      powerMw: 0,
      maxPowerMw: 34,
      status: "stable",
      critical: false,
      flexible: true,
      description: "Stockage tactique. Puissant, mais limite.",
    },
    {
      id: "datacenter",
      name: "Datacenter IA souverain",
      kind: "datacenter",
      category: "ai",
      position: { x: 74, y: 30 },
      powerMw: 21,
      maxPowerMw: 82,
      status: "stable",
      critical: true,
      flexible: true,
      description: "Charges IA de priorites differentes, a orchestrer selon le reseau.",
    },
    {
      id: "hospital",
      name: "Hopital prioritaire",
      kind: "load",
      category: "hospital",
      position: { x: 82, y: 66 },
      powerMw: 24,
      maxPowerMw: 28,
      status: "stable",
      critical: true,
      flexible: false,
      description: "Service critique. Toute degradation pese lourdement sur le score.",
    },
    {
      id: "residential",
      name: "Quartiers residentiels",
      kind: "load",
      category: "residential",
      position: { x: 62, y: 78 },
      powerMw: 44,
      maxPowerMw: 74,
      status: "stable",
      critical: false,
      flexible: false,
      description: "Demande du soir peu flexible, sensible a la temperature.",
    },
    {
      id: "industry",
      name: "Industrie strategique",
      kind: "load",
      category: "industry",
      position: { x: 48, y: 66 },
      powerMw: 42,
      maxPowerMw: 54,
      status: "stable",
      critical: true,
      flexible: true,
      description: "Charge importante avec une petite flexibilite operationnelle.",
    },
    {
      id: "ev",
      name: "Bornes EV",
      kind: "load",
      category: "ev",
      position: { x: 72, y: 84 },
      powerMw: 20,
      maxPowerMw: 56,
      status: "watch",
      critical: false,
      flexible: true,
      description: "Recharge massive et flexible si elle est lissee a temps.",
    },
    {
      id: "vivatech",
      name: "VivaGrid Live",
      kind: "load",
      category: "event",
      position: { x: 88, y: 44 },
      powerMw: 16,
      maxPowerMw: 26,
      status: "stable",
      critical: false,
      flexible: true,
      description: "Evenement public visible, sensible aux ralentissements IA.",
    },
  ],
  aiJobs: [
    {
      id: "assistant-public",
      name: "Assistant public salon",
      kind: "text",
      criticality: "medium",
      status: "active",
      basePowerMw: 8,
      currentPowerMw: 8,
      progress: 35,
      value: 12,
      startMinute: 17 * 60 + 30,
      deadlineMinute: 20 * 60 + 30,
      cached: false,
      modelScale: 1,
      timeoutApplied: false,
      loopRisk: 12,
      redundantCalls: 24,
      sovereign: true,
      narrative: "Support visiteurs et syntheses de conferences.",
    },
    {
      id: "dev-agent",
      name: "Agent developpeur hackathon",
      kind: "code",
      criticality: "medium",
      status: "active",
      basePowerMw: 13,
      currentPowerMw: 13,
      progress: 22,
      value: 18,
      startMinute: 17 * 60 + 30,
      deadlineMinute: 20 * 60,
      cached: false,
      modelScale: 1,
      timeoutApplied: false,
      loopRisk: 38,
      redundantCalls: 31,
      sovereign: true,
      narrative: "Aide au code pour les equipes du salon.",
    },
    {
      id: "video-demo",
      name: "Generation video stand",
      kind: "video",
      criticality: "low",
      status: "queued",
      basePowerMw: 30,
      currentPowerMw: 0,
      progress: 0,
      value: 14,
      startMinute: 18 * 60 + 30,
      deadlineMinute: 20 * 60 + 15,
      cached: false,
      modelScale: 1,
      timeoutApplied: false,
      loopRisk: 8,
      redundantCalls: 7,
      sovereign: true,
      narrative: "Contenu visuel non critique pour l'ecran principal.",
    },
    {
      id: "cyber-critical",
      name: "Detection cyber critique",
      kind: "cyber",
      criticality: "critical",
      status: "queued",
      basePowerMw: 24,
      currentPowerMw: 0,
      progress: 0,
      value: 34,
      startMinute: 19 * 60 + 10,
      deadlineMinute: 20 * 60 + 5,
      cached: false,
      modelScale: 1,
      timeoutApplied: false,
      loopRisk: 4,
      redundantCalls: 4,
      sovereign: true,
      narrative: "Analyse de menace a proteger absolument.",
    },
    {
      id: "looping-agent",
      name: "Agent autonome en boucle",
      kind: "agent",
      criticality: "medium",
      status: "queued",
      basePowerMw: 11,
      currentPowerMw: 0,
      progress: 0,
      value: 6,
      startMinute: 19 * 60 + 30,
      deadlineMinute: 20 * 60 + 30,
      cached: false,
      modelScale: 1,
      timeoutApplied: false,
      loopRisk: 86,
      redundantCalls: 72,
      sovereign: true,
      narrative: "Agent de demonstration qui risque d'explorer trop longtemps.",
    },
  ],
  events: [
    {
      id: "ev-surge",
      minute: 18 * 60,
      title: "Recharge EV avancee",
      description: "Les bornes de recharge demarrent plus tot que prevu.",
      severity: "warning",
    },
    {
      id: "video-job",
      minute: 18 * 60 + 30,
      title: "Job video non critique",
      description: "Le salon demande une generation video lourde pendant le pic.",
      severity: "warning",
    },
    {
      id: "solar-drop",
      minute: 18 * 60 + 50,
      title: "Chute solaire",
      description: "Le solaire baisse fortement pendant que le residentiel monte.",
      severity: "critical",
    },
    {
      id: "cyber-job",
      minute: 19 * 60 + 10,
      title: "Job cyber critique",
      description: "Un calcul de detection cyber prioritaire arrive au datacenter.",
      severity: "critical",
    },
    {
      id: "agent-loop",
      minute: 19 * 60 + 30,
      title: "Energy SOC: agent en boucle",
      description: "Un agent IA multiplie les appels redondants sans valeur utile.",
      severity: "critical",
    },
  ],
};
