import type { Scenario } from "@/game/types";

export const eveningPeakScenario: Scenario = {
  id: "evening-peak",
  mapId: "france-national",
  difficulty: "standard",
  name: "Le pic de 19h",
  subtitle:
    "Gérez une fin de journée sous tension pendant que le datacenter IA lance ses jobs critiques.",
  startMinute: 17 * 60 + 30,
  endMinute: 20 * 60 + 30,
  tickMinutes: 5,
  objectives: [
    "Maintenir la stabilité réseau au-dessus de 50.",
    "Préserver l'hôpital et le job cyber critique.",
    "Optimiser les charges IA flexibles sans couper l'IA utile.",
    "Éviter le thermique sauf urgence.",
  ],
  objectiveChecks: [
    {
      id: "stable-grid",
      label: "Stabilité finale >= 45%",
      metric: "stability",
      operator: ">=",
      target: 45,
      required: true,
    },
    {
      id: "critical-services",
      label: "Continuité critique >= 75%",
      metric: "criticalContinuity",
      operator: ">=",
      target: 75,
      required: true,
    },
    {
      id: "no-critical-ai-failure",
      label: "Aucun job IA critique échoué",
      metric: "failedCriticalJobs",
      operator: "=",
      target: 0,
      required: true,
    },
    {
      id: "few-line-trips",
      label: "Moins de 2 déclenchements de ligne",
      metric: "lineTrips",
      operator: "<=",
      target: 1,
    },
  ],
  commandCapacity: 100,
  knownEventIds: ["ev-surge", "solar-drop"],
  rewards: ["medal-security", "tool-migration-ai", "map-corsica"],
  initialMetrics: {
    stability: 85,
    carbon: 86,
    cost: 78,
    sovereignty: 90,
    aiProductivity: 60,
    publicSatisfaction: 80,
    criticalContinuity: 100,
    batteryLevel: 65,
    productionMw: 172,
    demandMw: 161,
    aiLoadMw: 21,
    reserveMw: 11,
    co2Intensity: 44,
    score: 735,
  },
  assets: [
    {
      id: "nuclear",
      name: "Socle nucléaire",
      kind: "production",
      category: "nuclear",
      position: { x: 16, y: 28 },
      powerMw: 96,
      maxPowerMw: 96,
      status: "stable",
      critical: false,
      flexible: false,
      description: "Production bas carbone stable mais peu flexible à court terme.",
    },
    {
      id: "solar",
      name: "Parc solaire",
      kind: "production",
      category: "solar",
      position: { x: 32, y: 18 },
      powerMw: 28,
      maxPowerMw: 34,
      status: "watch",
      critical: false,
      flexible: false,
      description: "Production utile en journée, en baisse rapide avant le pic du soir.",
    },
    {
      id: "wind",
      name: "Éolien Atlantique",
      kind: "production",
      category: "wind",
      position: { x: 17, y: 72 },
      powerMw: 20,
      maxPowerMw: 34,
      status: "stable",
      critical: false,
      flexible: false,
      description: "Production variable avec incertitude météo.",
    },
    {
      id: "hydro",
      name: "Hydraulique réserve",
      kind: "production",
      category: "hydro",
      position: { x: 34, y: 82 },
      powerMw: 26,
      maxPowerMw: 34,
      status: "stable",
      critical: false,
      flexible: true,
      description: "Réserve pilotable gardée pour absorber les pointes.",
    },
    {
      id: "battery",
      name: "Batteries réseau",
      kind: "storage",
      category: "battery",
      position: { x: 50, y: 28 },
      powerMw: 0,
      maxPowerMw: 34,
      status: "stable",
      critical: false,
      flexible: true,
      description: "Stockage tactique. Puissant, mais limité.",
    },
    {
      id: "datacenter",
      name: "Datacenter IA souverain",
      kind: "datacenter",
      category: "ai",
      position: { x: 74, y: 30 },
      powerMw: 21,
      maxPowerMw: 82,
      status: "stable",
      critical: true,
      flexible: true,
      description: "Charges IA de priorités différentes, à orchestrer selon le réseau.",
    },
    {
      id: "hospital",
      name: "Hôpital prioritaire",
      kind: "load",
      category: "hospital",
      position: { x: 82, y: 66 },
      powerMw: 24,
      maxPowerMw: 28,
      status: "stable",
      critical: true,
      flexible: false,
      description: "Service critique. Toute dégradation pèse lourdement sur le score.",
    },
    {
      id: "residential",
      name: "Quartiers résidentiels",
      kind: "load",
      category: "residential",
      position: { x: 62, y: 78 },
      powerMw: 44,
      maxPowerMw: 74,
      status: "stable",
      critical: false,
      flexible: false,
      description: "Demande du soir peu flexible, sensible à la température.",
    },
    {
      id: "industry",
      name: "Industrie stratégique",
      kind: "load",
      category: "industry",
      position: { x: 48, y: 66 },
      powerMw: 42,
      maxPowerMw: 54,
      status: "stable",
      critical: true,
      flexible: true,
      description: "Charge importante avec une petite flexibilité opérationnelle.",
    },
    {
      id: "ev",
      name: "Bornes EV",
      kind: "load",
      category: "ev",
      position: { x: 72, y: 84 },
      powerMw: 20,
      maxPowerMw: 56,
      status: "watch",
      critical: false,
      flexible: true,
      description: "Recharge massive et flexible si elle est lissée à temps.",
    },
    {
      id: "vivatech",
      name: "VivaGrid Live",
      kind: "load",
      category: "event",
      position: { x: 88, y: 44 },
      powerMw: 16,
      maxPowerMw: 26,
      status: "stable",
      critical: false,
      flexible: true,
      description: "Événement public visible, sensible aux ralentissements IA.",
    },
  ],
  aiJobs: [
    {
      id: "assistant-public",
      name: "Assistant public salon",
      kind: "text",
      criticality: "medium",
      status: "active",
      basePowerMw: 8,
      currentPowerMw: 8,
      progress: 35,
      value: 12,
      startMinute: 17 * 60 + 30,
      deadlineMinute: 20 * 60 + 30,
      cached: false,
      modelScale: 1,
      timeoutApplied: false,
      loopRisk: 12,
      redundantCalls: 24,
      sovereign: true,
      assignedNodeId: "paris-saclay-ai",
      preferredNodeIds: ["paris-saclay-ai", "grenoble-ai-edge"],
      externalized: false,
      narrative: "Support visiteurs et synthèses de conférences.",
    },
    {
      id: "dev-agent",
      name: "Agent développeur hackathon",
      kind: "code",
      criticality: "medium",
      status: "active",
      basePowerMw: 13,
      currentPowerMw: 13,
      progress: 22,
      value: 18,
      startMinute: 17 * 60 + 30,
      deadlineMinute: 20 * 60,
      cached: false,
      modelScale: 1,
      timeoutApplied: false,
      loopRisk: 38,
      redundantCalls: 31,
      sovereign: true,
      assignedNodeId: "paris-saclay-ai",
      preferredNodeIds: ["paris-saclay-ai", "grenoble-ai-edge"],
      externalized: false,
      narrative: "Aide au code pour les équipes du salon.",
    },
    {
      id: "video-demo",
      name: "Génération vidéo stand",
      kind: "video",
      criticality: "low",
      status: "queued",
      basePowerMw: 30,
      currentPowerMw: 0,
      progress: 0,
      value: 14,
      startMinute: 18 * 60 + 30,
      deadlineMinute: 20 * 60 + 15,
      cached: false,
      modelScale: 1,
      timeoutApplied: false,
      loopRisk: 8,
      redundantCalls: 7,
      sovereign: false,
      assignedNodeId: "paris-saclay-ai",
      preferredNodeIds: ["grenoble-ai-edge", "paris-saclay-ai"],
      externalized: false,
      narrative: "Contenu visuel non critique pour l'écran principal.",
    },
    {
      id: "cyber-critical",
      name: "Détection cyber critique",
      kind: "cyber",
      criticality: "critical",
      status: "queued",
      basePowerMw: 24,
      currentPowerMw: 0,
      progress: 0,
      value: 34,
      startMinute: 19 * 60 + 10,
      deadlineMinute: 20 * 60 + 5,
      cached: false,
      modelScale: 1,
      timeoutApplied: false,
      loopRisk: 4,
      redundantCalls: 4,
      sovereign: true,
      assignedNodeId: "paris-saclay-ai",
      preferredNodeIds: ["paris-saclay-ai"],
      externalized: false,
      narrative: "Analyse de menace à protéger absolument.",
    },
    {
      id: "looping-agent",
      name: "Agent autonome en boucle",
      kind: "agent",
      criticality: "medium",
      status: "queued",
      basePowerMw: 11,
      currentPowerMw: 0,
      progress: 0,
      value: 6,
      startMinute: 19 * 60 + 30,
      deadlineMinute: 20 * 60 + 30,
      cached: false,
      modelScale: 1,
      timeoutApplied: false,
      loopRisk: 86,
      redundantCalls: 72,
      sovereign: true,
      assignedNodeId: "grenoble-ai-edge",
      preferredNodeIds: ["grenoble-ai-edge", "paris-saclay-ai"],
      externalized: false,
      narrative: "Agent de démonstration qui risque d'explorer trop longtemps.",
    },
  ],
  events: [
    {
      id: "ev-surge",
      minute: 18 * 60,
      title: "Recharge EV avancée",
      description: "Les bornes de recharge démarrent plus tôt que prévu.",
      severity: "warning",
      source: "grid",
      effects: [{ type: "set_flag", flag: "evSurge", value: true }],
      resolvesWhen: [{ type: "effect_active", action: "smart_ev" }],
    },
    {
      id: "video-job",
      minute: 18 * 60 + 30,
      title: "Job vidéo non critique",
      description: "Le salon demande une génération vidéo lourde pendant le pic.",
      severity: "warning",
      source: "ai",
      effects: [{ type: "activate_ai_job", jobId: "video-demo" }],
      resolvesWhen: [{ type: "job_status", jobId: "video-demo", statuses: ["deferred", "completed"] }],
    },
    {
      id: "solar-drop",
      minute: 18 * 60 + 50,
      title: "Chute solaire",
      description: "Le solaire baisse fortement pendant que le résidentiel monte.",
      severity: "critical",
      source: "weather",
      effects: [
        { type: "set_flag", flag: "solarDrop", value: true },
        { type: "set_flag", flag: "residentialPeak", value: true },
      ],
      resolvesWhen: [{ type: "stability_above", threshold: 54, flag: "solarDrop" }],
    },
    {
      id: "cyber-job",
      minute: 19 * 60 + 10,
      title: "Job cyber critique",
      description: "Un calcul de détection cyber prioritaire arrive au datacenter.",
      severity: "critical",
      source: "ai",
      effects: [
        { type: "set_flag", flag: "cyberPriority", value: true },
        { type: "activate_ai_job", jobId: "cyber-critical" },
      ],
      resolvesWhen: [{ type: "job_status", jobId: "cyber-critical", statuses: ["completed"] }],
    },
    {
      id: "agent-loop",
      minute: 19 * 60 + 30,
      title: "Energy SOC: agent en boucle",
      description: "Un agent IA multiplie les appels redondants sans valeur utile.",
      severity: "critical",
      source: "ai",
      effects: [
        { type: "set_flag", flag: "agentLoop", value: true },
        { type: "activate_ai_job", jobId: "looping-agent" },
      ],
      resolvesWhen: [{ type: "flag_false", flag: "agentLoop" }],
    },
  ],
};
