import type { MapDefinition } from "@/game/domain/mapDefinition";

export const mapRegistry: MapDefinition[] = [
  {
    id: "vivatech-campus",
    name: "Microgrid VivaTech",
    terrain: "microgrid",
    description: "Réseau compact de tutoriel avec batterie, stand public, bornes EV et datacenter local.",
    nodeIds: [
      "normandy-production",
      "interconnect-north",
      "paris-saclay-ai",
      "idf-hospital",
      "centre-battery",
      "bordeaux-ev",
    ],
    lineIds: [
      "normandy-paris",
      "normandy-interconnect",
      "interconnect-paris",
      "paris-hospital",
      "paris-centre-battery",
      "bordeaux-centre",
    ],
    cameraPreset: "close",
    modelScale: 1.25,
    environment: "expo-floor",
    availableLayers: ["grid", "ai"],
  },
  {
    id: "france-national",
    name: "France nationale",
    terrain: "france",
    description: "Carte nationale avec production bas carbone, datacenters souverains et corridors haute tension.",
    cameraPreset: "national",
    modelScale: 1,
    environment: "command-night",
    availableLayers: ["grid", "ai", "carbon"],
  },
  {
    id: "black-grid-night",
    name: "Black Grid",
    terrain: "france",
    description: "Carte nationale de nuit avec télémétrie partielle, cyberattaque et lignes fantômes.",
    cameraPreset: "national",
    modelScale: 1,
    environment: "command-night",
    availableLayers: ["grid", "ai", "carbon"],
  },
  {
    id: "rhone-corridor",
    name: "Couloir Rhône",
    terrain: "regional",
    description: "Réseau sud-est resserré autour de Lyon, production Rhône, industrie et datacenter edge.",
    nodeIds: [
      "interconnect-north",
      "paris-saclay-ai",
      "centre-battery",
      "bordeaux-ev",
      "southwest-solar",
      "rhone-production",
      "lyon-industry",
      "grenoble-ai-edge",
      "marseille-load",
    ],
    lineIds: [
      "interconnect-paris",
      "paris-lyon",
      "paris-centre-battery",
      "bordeaux-centre",
      "bordeaux-toulouse",
      "solar-rhone",
      "centre-lyon",
      "lyon-marseille",
      "rhone-grenoble-edge",
    ],
    cameraPreset: "regional",
    modelScale: 1.08,
    environment: "command-night",
    availableLayers: ["grid", "ai", "carbon"],
  },
  {
    id: "europe-2030",
    name: "Europe 2030",
    terrain: "europe",
    description: "Finale avec interconnexions européennes, prix carbone et solidarité transfrontalière.",
    cameraPreset: "europe",
    modelScale: 0.98,
    environment: "command-night",
    availableLayers: ["grid", "ai", "carbon"],
  },
  {
    id: "corsica-island",
    name: "Corse isolée",
    terrain: "island",
    description: "Réseau insulaire contraint par solaire, stockage et interconnexion limitée.",
    nodeIds: [
      "interconnect-north",
      "paris-saclay-ai",
      "idf-hospital",
      "centre-battery",
      "bordeaux-ev",
      "southwest-solar",
      "rhone-production",
      "lyon-industry",
      "marseille-load",
      "grenoble-ai-edge",
    ],
    lineIds: [
      "interconnect-paris",
      "paris-hospital",
      "paris-centre-battery",
      "bordeaux-centre",
      "bordeaux-toulouse",
      "solar-rhone",
      "centre-lyon",
      "paris-lyon",
      "lyon-marseille",
      "rhone-grenoble-edge",
    ],
    cameraPreset: "regional",
    modelScale: 1.1,
    environment: "island-dusk",
    availableLayers: ["grid", "carbon"],
  },
];

export function getMapDefinition(mapId: string) {
  return mapRegistry.find((map) => map.id === mapId) ?? mapRegistry[1];
}
