import { eveningPeakScenario } from "@/game/scenarios/eveningPeak";
import type { MissionDefinition } from "@/game/domain/missionDefinition";
import type { PlayerActionType, Scenario } from "@/game/types";

function cloneScenario(scenario: Scenario): Scenario {
  return JSON.parse(JSON.stringify(scenario)) as Scenario;
}

type ScenarioVariantInput = Omit<Partial<Scenario>, "initialMetrics"> & {
  initialMetrics?: Partial<Scenario["initialMetrics"]>;
};

function scenarioVariant(overrides: ScenarioVariantInput): Scenario {
  return {
    ...cloneScenario(eveningPeakScenario),
    ...overrides,
    initialMetrics: {
      ...eveningPeakScenario.initialMetrics,
      ...overrides.initialMetrics,
    },
  };
}

const basicGridActions: PlayerActionType[] = [
  "discharge_battery",
  "smart_ev",
  "import_energy",
  "thermal_backup",
];
const tutorialActions: PlayerActionType[] = ["discharge_battery", "smart_ev", "defer_ai"];
const aiActions: PlayerActionType[] = [
  "defer_ai",
  "migrate_ai",
  "reduce_model",
  "activate_cache",
  "agent_timeout",
];
const lineActions: PlayerActionType[] = ["reroute_line", "repair_line", "authorize_overload"];
const industryActions: PlayerActionType[] = ["curtail_industry"];
const sovereignActions: PlayerActionType[] = ["externalize_ai"];

function actions(...groups: PlayerActionType[][]): PlayerActionType[] {
  return [...new Set(groups.flat())];
}

export const missionRegistry: MissionDefinition[] = [
  {
    id: "tutorial-microgrid",
    mapId: "vivatech-campus",
    title: "Première garde",
    subtitle: "Apprendre batterie, surcharge et continuité critique sur un microgrid.",
    newMechanic: "Batterie et lecture d'une ligne chaude",
    medalThresholds: { bronze: 540, silver: 690, gold: 820 },
    scenario: scenarioVariant({
      id: "tutorial-microgrid",
      mapId: "vivatech-campus",
      difficulty: "tutorial",
      name: "Première garde",
      subtitle: "Tutoriel jouable sur un microgrid VivaTech.",
      startMinute: 18 * 60,
      endMinute: 19 * 60 + 30,
      commandCapacity: 70,
      availableActions: tutorialActions,
      knownEventIds: ["ev-surge", "video-job"],
      objectives: [
        "Cliquer une ligne en surcharge.",
        "Décharger la batterie sans vider la réserve.",
        "Terminer avec les services critiques en ligne.",
      ],
      objectiveChecks: [
        {
          id: "tutorial-continuity",
          label: "Services critiques préservés",
          metric: "criticalContinuity",
          operator: ">=",
          target: 90,
          required: true,
        },
        {
          id: "tutorial-battery-discipline",
          label: "Capacité dépensée <= 75 CP",
          metric: "commandCapacitySpent",
          operator: "<=",
          target: 75,
        },
        {
          id: "tutorial-no-trip",
          label: "Aucune ligne déclenchée",
          metric: "lineTrips",
          operator: "=",
          target: 0,
        },
      ],
      events: eveningPeakScenario.events.filter((event) => ["ev-surge", "video-job"].includes(event.id)),
      rewards: ["mission-paris-peak", "tool-smart-ev"],
    }),
  },
  {
    id: "paris-peak",
    mapId: "france-national",
    title: "Paris sous tension",
    subtitle: "EV, jobs IA flexibles et hôpital prioritaire en Île-de-France.",
    unlockAfter: "tutorial-microgrid",
    newMechanic: "Jobs IA, cache et migration vers Grenoble",
    medalThresholds: { bronze: 570, silver: 720, gold: 850 },
    scenario: scenarioVariant({
      id: "paris-peak",
      mapId: "france-national",
      difficulty: "standard",
      name: "Paris sous tension",
      commandCapacity: 100,
      availableActions: actions(basicGridActions, aiActions),
      knownEventIds: ["ev-surge", "solar-drop"],
      objectiveChecks: [
        ...eveningPeakScenario.objectiveChecks,
        {
          id: "paris-ai-jobs",
          label: "Au moins 3 jobs IA terminés",
          metric: "completedAiJobs",
          operator: ">=",
          target: 3,
        },
      ],
      rewards: ["mission-corsica-islanding", "tool-ai-migration"],
    }),
  },
  {
    id: "corsica-islanding",
    mapId: "corsica-island",
    title: "L’île énergétique",
    subtitle: "Stockage limité, chute solaire et import contraint.",
    unlockAfter: "paris-peak",
    newMechanic: "Mode îloté et réserve de stockage",
    medalThresholds: { bronze: 560, silver: 710, gold: 835 },
    scenario: scenarioVariant({
      id: "corsica-islanding",
      mapId: "corsica-island",
      difficulty: "standard",
      name: "L’île énergétique",
      commandCapacity: 116,
      availableActions: actions(basicGridActions, aiActions),
      knownEventIds: ["solar-drop"],
      initialMetrics: {
        batteryLevel: 82,
        sovereignty: 94,
        cost: 72,
      },
      objectiveChecks: [
        ...eveningPeakScenario.objectiveChecks,
        {
          id: "corsica-low-unserved",
          label: "Énergie non servie <= 80 MWh",
          metric: "unservedEnergyMwh",
          operator: "<=",
          target: 80,
        },
      ],
      rewards: ["mission-atlantic-storm", "mode-crisis-run"],
    }),
  },
  {
    id: "atlantic-storm",
    mapId: "france-national",
    title: "Tempête Atlantique",
    subtitle: "Vent incertain, ligne ouest affaiblie et reroutage sous pression.",
    unlockAfter: "corsica-islanding",
    newMechanic: "Reroutage et réparation de ligne",
    medalThresholds: { bronze: 590, silver: 735, gold: 860 },
    scenario: scenarioVariant({
      id: "atlantic-storm",
      mapId: "france-national",
      difficulty: "hard",
      name: "Tempête Atlantique",
      commandCapacity: 92,
      availableActions: actions(basicGridActions, aiActions, lineActions),
      knownEventIds: ["ev-surge"],
      initialMetrics: {
        stability: 78,
        batteryLevel: 58,
      },
      objectiveChecks: [
        ...eveningPeakScenario.objectiveChecks,
        {
          id: "storm-control-trips",
          label: "Au plus 1 déclenchement de ligne",
          metric: "lineTrips",
          operator: "<=",
          target: 1,
          required: true,
        },
      ],
      rewards: ["mission-rhone-corridor", "tool-repair-line"],
    }),
  },
  {
    id: "rhone-corridor",
    mapId: "rhone-corridor",
    title: "Couloir Rhône",
    subtitle: "Industrie, congestion sud-est et effacement sous contrainte.",
    unlockAfter: "atlantic-storm",
    newMechanic: "Effacement industriel et cascade nord-sud",
    medalThresholds: { bronze: 330, silver: 650, gold: 850 },
    scenario: scenarioVariant({
      id: "rhone-corridor",
      mapId: "rhone-corridor",
      difficulty: "hard",
      name: "Couloir Rhône",
      subtitle: "La vallée du Rhône concentre industrie, recharge, IA edge et flux vers PACA.",
      commandCapacity: 102,
      availableActions: actions(basicGridActions, aiActions, lineActions, industryActions),
      knownEventIds: ["ev-surge", "rhone-industry-surge"],
      initialMetrics: {
        stability: 76,
        batteryLevel: 64,
        cost: 70,
        publicSatisfaction: 78,
      },
      objectives: [
        "Maintenir le corridor Rhône-Lyon sous contrôle thermique.",
        "Effacer l'industrie seulement si le coût reste acceptable.",
        "Préserver le datacenter Grenoble et le résidentiel PACA.",
      ],
      objectiveChecks: [
        {
          id: "rhone-stability",
          label: "Stabilité finale >= 48%",
          metric: "stability",
          operator: ">=",
          target: 48,
          required: true,
        },
        {
          id: "rhone-continuity",
          label: "Continuité critique >= 82%",
          metric: "criticalContinuity",
          operator: ">=",
          target: 82,
          required: true,
        },
        {
          id: "rhone-cost",
          label: "Score coût >= 42%",
          metric: "cost",
          operator: ">=",
          target: 42,
        },
        {
          id: "rhone-trips",
          label: "Au plus 2 déclenchements de ligne",
          metric: "lineTrips",
          operator: "<=",
          target: 2,
          required: true,
        },
      ],
      events: [
        {
          id: "ev-surge",
          minute: 18 * 60,
          title: "Recharge autoroute A7",
          description: "Les bornes rapides montent pendant que le couloir nord-sud est déjà chargé.",
          severity: "warning",
          source: "grid",
          effects: [{ type: "set_flag", flag: "evSurge", value: true }],
          resolvesWhen: [{ type: "effect_active", action: "smart_ev" }],
        },
        {
          id: "rhone-industry-surge",
          minute: 18 * 60 + 30,
          title: "Four industriel Lyon",
          description: "L'industrie lyonnaise maintient sa production et pousse le corridor au-delà de sa marge.",
          severity: "warning",
          source: "grid",
          effects: [{ type: "set_flag", flag: "residentialPeak", value: true }],
        },
        {
          id: "solar-drop",
          minute: 18 * 60 + 50,
          title: "Solaire sud-est en baisse",
          description: "Le solaire décroche au moment où PACA et l'industrie restent hauts.",
          severity: "critical",
          source: "weather",
          effects: [
            { type: "set_flag", flag: "solarDrop", value: true },
            { type: "set_flag", flag: "residentialPeak", value: true },
          ],
          resolvesWhen: [{ type: "stability_above", threshold: 54, flag: "solarDrop" }],
        },
        {
          id: "rhone-line-trip",
          minute: 19 * 60 + 10,
          title: "Protection Centre-Lyon",
          description: "Une protection ouvre le lien Centre-Lyon et reporte le flux vers Paris-Lyon et Rhône.",
          severity: "critical",
          source: "grid",
          effects: [{ type: "trip_line", lineId: "centre-lyon" }],
        },
        {
          id: "video-job",
          minute: 19 * 60 + 20,
          title: "Job IA edge Grenoble",
          description: "Un job non critique démarre sur Grenoble alors que la ligne Rhône-Grenoble chauffe.",
          severity: "warning",
          source: "ai",
          effects: [{ type: "activate_ai_job", jobId: "video-demo" }],
          resolvesWhen: [{ type: "job_status", jobId: "video-demo", statuses: ["deferred", "completed"] }],
        },
        {
          id: "agent-loop",
          minute: 19 * 60 + 45,
          title: "Agent logistique divergent",
          description: "Un agent optimise la logistique industrielle sans valeur et consomme trop d'IA edge.",
          severity: "critical",
          source: "ai",
          effects: [
            { type: "set_flag", flag: "agentLoop", value: true },
            { type: "activate_ai_job", jobId: "looping-agent" },
          ],
          resolvesWhen: [{ type: "flag_false", flag: "agentLoop" }],
        },
      ],
      rewards: ["mission-sovereign-ai"],
    }),
  },
  {
    id: "sovereign-ai",
    mapId: "france-national",
    title: "Souveraineté numérique",
    subtitle: "Choisir entre migration locale, import coûteux et productivité IA.",
    unlockAfter: "rhone-corridor",
    newMechanic: "Doctrine souveraine et score cumulatif",
    medalThresholds: { bronze: 610, silver: 760, gold: 880 },
    scenario: scenarioVariant({
      id: "sovereign-ai",
      mapId: "france-national",
      difficulty: "expert",
      name: "Souveraineté numérique",
      commandCapacity: 82,
      availableActions: actions(basicGridActions, aiActions, lineActions, industryActions, sovereignActions),
      knownEventIds: [],
      initialMetrics: {
        sovereignty: 96,
        stability: 76,
        cost: 70,
      },
      objectiveChecks: [
        ...eveningPeakScenario.objectiveChecks,
        {
          id: "sovereign-no-athena",
          label: "ATHENA autopilot non utilisé",
          metric: "athenaAutopilotUses",
          operator: "=",
          target: 0,
        },
      ],
      rewards: ["mission-black-grid", "mode-daily-challenge"],
    }),
  },
  {
    id: "black-grid",
    mapId: "black-grid-night",
    title: "Black Grid",
    subtitle: "Cyberattaque, télémétrie partielle et incident fantôme sur le réseau national.",
    unlockAfter: "sovereign-ai",
    newMechanic: "Télémétrie incertaine et lignes fantômes",
    medalThresholds: { bronze: 625, silver: 775, gold: 895 },
    scenario: scenarioVariant({
      id: "black-grid",
      mapId: "black-grid-night",
      difficulty: "expert",
      name: "Black Grid",
      subtitle: "La supervision nationale reçoit des données partielles pendant une attaque cyber.",
      commandCapacity: 136,
      availableActions: actions(basicGridActions, aiActions, lineActions, industryActions, sovereignActions),
      knownEventIds: [],
      telemetry: {
        mode: "blackout",
        label: "Flux SCADA partiel",
        metricNoisePct: 12,
        forecastHorizonMinutes: 5,
        hiddenLineIds: ["paris-lyon", "rhone-grenoble-edge"],
        hiddenNodeIds: ["paris-saclay-ai", "idf-hospital"],
        phantomLineIds: ["paris-lyon"],
      },
      initialMetrics: {
        stability: 74,
        batteryLevel: 62,
        sovereignty: 98,
        publicSatisfaction: 76,
      },
      objectives: [
        "Maintenir les services critiques malgré la télémétrie partielle.",
        "Identifier et absorber l'incident fantôme sans sacrifier le job cyber.",
        "Limiter les déclenchements de lignes pendant l'attaque.",
      ],
      objectiveChecks: [
        {
          id: "black-grid-stability",
          label: "Stabilité finale >= 40%",
          metric: "stability",
          operator: ">=",
          target: 40,
          required: true,
        },
        {
          id: "black-grid-continuity",
          label: "Continuité critique >= 78%",
          metric: "criticalContinuity",
          operator: ">=",
          target: 78,
          required: true,
        },
        {
          id: "black-grid-cyber",
          label: "Job cyber critique préservé",
          metric: "failedCriticalJobs",
          operator: "=",
          target: 0,
          required: true,
        },
        {
          id: "black-grid-line-trips",
          label: "Au plus 2 déclenchements de ligne",
          metric: "lineTrips",
          operator: "<=",
          target: 2,
        },
      ],
      events: [
        {
          id: "ev-surge",
          minute: 18 * 60,
          title: "Recharge EV masquée",
          description: "Les bornes montent en charge mais le signal arrive avec retard.",
          severity: "warning",
          source: "grid",
          effects: [{ type: "set_flag", flag: "evSurge", value: true }],
          resolvesWhen: [{ type: "effect_active", action: "smart_ev" }],
        },
        {
          id: "video-job",
          minute: 18 * 60 + 25,
          title: "Charge IA parasite",
          description: "Un job vidéo non critique démarre pendant que la supervision perd des mesures.",
          severity: "warning",
          source: "ai",
          effects: [{ type: "activate_ai_job", jobId: "video-demo" }],
          resolvesWhen: [{ type: "job_status", jobId: "video-demo", statuses: ["deferred", "completed"] }],
        },
        {
          id: "phantom-paris-lyon",
          minute: 18 * 60 + 40,
          title: "Ligne fantôme Paris-Lyon",
          description: "Le corridor paraît disponible dans SCADA mais sa protection a déclenché localement.",
          severity: "critical",
          source: "grid",
          effects: [{ type: "trip_line", lineId: "paris-lyon" }],
        },
        {
          id: "solar-drop",
          minute: 18 * 60 + 50,
          title: "Chute solaire non confirmée",
          description: "Le solaire baisse au moment où le résidentiel monte, mais les mesures restent bruitées.",
          severity: "critical",
          source: "weather",
          effects: [
            { type: "set_flag", flag: "solarDrop", value: true },
            { type: "set_flag", flag: "residentialPeak", value: true },
          ],
          resolvesWhen: [{ type: "stability_above", threshold: 54, flag: "solarDrop" }],
        },
        {
          id: "cyber-job",
          minute: 19 * 60 + 5,
          title: "Détection cyber prioritaire",
          description: "Le calcul critique doit rester souverain malgré la saturation du réseau.",
          severity: "critical",
          source: "ai",
          effects: [
            { type: "set_flag", flag: "cyberPriority", value: true },
            { type: "activate_ai_job", jobId: "cyber-critical" },
          ],
          resolvesWhen: [{ type: "job_status", jobId: "cyber-critical", statuses: ["completed"] }],
        },
        {
          id: "agent-loop",
          minute: 19 * 60 + 25,
          title: "Agent autonome divergent",
          description: "Un agent consomme sans valeur utile et brouille les priorités IA.",
          severity: "critical",
          source: "ai",
          effects: [
            { type: "set_flag", flag: "agentLoop", value: true },
            { type: "activate_ai_job", jobId: "looping-agent" },
          ],
          resolvesWhen: [{ type: "flag_false", flag: "agentLoop" }],
        },
        {
          id: "telemetry-spoof",
          minute: 19 * 60 + 45,
          title: "Usurpation de télémétrie",
          description: "ATHENA détecte une incohérence de charge, mais pas sa source exacte.",
          severity: "warning",
          source: "grid",
          effects: [{ type: "set_flag", flag: "residentialPeak", value: true }],
        },
      ],
      rewards: ["mission-europe-2030"],
    }),
  },
  {
    id: "europe-2030",
    mapId: "europe-2030",
    title: "Finale · Europe 2030",
    subtitle: "Prix, carbone et solidarité européenne pendant une crise simultanée.",
    unlockAfter: "black-grid",
    newMechanic: "Arbitrage Europe : importer, préserver le carbone ou délester les contrats",
    medalThresholds: { bronze: 640, silver: 790, gold: 910 },
    scenario: scenarioVariant({
      id: "europe-2030",
      mapId: "europe-2030",
      difficulty: "expert",
      name: "Europe 2030",
      subtitle: "La France doit stabiliser son réseau tout en répondant à une crise européenne synchronisée.",
      commandCapacity: 132,
      availableActions: actions(basicGridActions, aiActions, lineActions, industryActions, sovereignActions),
      knownEventIds: ["ev-surge"],
      telemetry: {
        mode: "degraded",
        label: "Marché UE sous tension",
        metricNoisePct: 6,
        forecastHorizonMinutes: 10,
      },
      initialMetrics: {
        stability: 72,
        batteryLevel: 68,
        sovereignty: 88,
        carbon: 78,
        cost: 64,
        publicSatisfaction: 80,
      },
      objectives: [
        "Maintenir les services critiques malgré la congestion européenne.",
        "Utiliser la solidarité transfrontalière sans perdre la maîtrise carbone.",
        "Préserver le job cyber souverain et limiter les déclenchements de lignes.",
      ],
      objectiveChecks: [
        {
          id: "europe-stability",
          label: "Stabilité finale >= 50%",
          metric: "stability",
          operator: ">=",
          target: 50,
          required: true,
        },
        {
          id: "europe-critical",
          label: "Continuité critique >= 86%",
          metric: "criticalContinuity",
          operator: ">=",
          target: 86,
          required: true,
        },
        {
          id: "europe-cyber",
          label: "Job cyber critique préservé",
          metric: "failedCriticalJobs",
          operator: "=",
          target: 0,
          required: true,
        },
        {
          id: "europe-carbon",
          label: "Score CO₂ >= 45%",
          metric: "carbon",
          operator: ">=",
          target: 45,
        },
        {
          id: "europe-sovereignty",
          label: "Souveraineté >= 65%",
          metric: "sovereignty",
          operator: ">=",
          target: 65,
        },
        {
          id: "europe-line-trips",
          label: "Au plus 2 déclenchements de ligne",
          metric: "lineTrips",
          operator: "<=",
          target: 2,
        },
      ],
      events: [
        {
          id: "ev-surge",
          minute: 18 * 60,
          title: "Recharge européenne synchronisée",
          description: "La demande EV française monte au même moment que les pays voisins sollicitent les interconnexions.",
          severity: "warning",
          source: "grid",
          effects: [{ type: "set_flag", flag: "evSurge", value: true }],
          resolvesWhen: [{ type: "effect_active", action: "smart_ev" }],
        },
        {
          id: "video-job",
          minute: 18 * 60 + 20,
          title: "Démonstration IA européenne",
          description: "Un job vidéo non critique démarre pendant la montée des prix spot.",
          severity: "warning",
          source: "ai",
          effects: [{ type: "activate_ai_job", jobId: "video-demo" }],
          resolvesWhen: [{ type: "job_status", jobId: "video-demo", statuses: ["deferred", "completed"] }],
        },
        {
          id: "europe-price-spike",
          minute: 18 * 60 + 35,
          title: "Prix spot nord-européen",
          description: "Les imports restent possibles, mais chaque MW consommé hors plan coûte cher en score économique.",
          severity: "warning",
          source: "grid",
          effects: [{ type: "set_flag", flag: "residentialPeak", value: true }],
        },
        {
          id: "solar-drop",
          minute: 18 * 60 + 50,
          title: "Décrochage solaire continental",
          description: "Le solaire chute sur plusieurs pays, ce qui rend les arbitrages carbone plus tendus.",
          severity: "critical",
          source: "weather",
          effects: [
            { type: "set_flag", flag: "solarDrop", value: true },
            { type: "set_flag", flag: "residentialPeak", value: true },
          ],
          resolvesWhen: [{ type: "stability_above", threshold: 54, flag: "solarDrop" }],
        },
        {
          id: "interconnector-congestion",
          minute: 19 * 60 + 10,
          title: "Protection interconnexion nord",
          description: "La ligne Europe Nord déclenche localement. Il faut réparer ou absorber le report de flux.",
          severity: "critical",
          source: "grid",
          effects: [{ type: "trip_line", lineId: "normandy-interconnect" }],
        },
        {
          id: "cyber-job",
          minute: 19 * 60 + 20,
          title: "Coordination cyber ENTSO-E",
          description: "Le calcul cyber critique doit rester souverain malgré la congestion continentale.",
          severity: "critical",
          source: "ai",
          effects: [
            { type: "set_flag", flag: "cyberPriority", value: true },
            { type: "activate_ai_job", jobId: "cyber-critical" },
          ],
          resolvesWhen: [{ type: "job_status", jobId: "cyber-critical", statuses: ["completed"] }],
        },
        {
          id: "agent-loop",
          minute: 19 * 60 + 40,
          title: "Agent marché divergent",
          description: "Un agent d'optimisation de marché consomme sans valeur et amplifie le bruit opérationnel.",
          severity: "critical",
          source: "ai",
          effects: [
            { type: "set_flag", flag: "agentLoop", value: true },
            { type: "activate_ai_job", jobId: "looping-agent" },
          ],
          resolvesWhen: [{ type: "flag_false", flag: "agentLoop" }],
        },
      ],
      rewards: ["hackathon-complete"],
    }),
  },
];

export const defaultMissionId = "tutorial-microgrid";

export function getMissionDefinition(id: string) {
  return missionRegistry.find((mission) => mission.id === id) ?? missionRegistry.find((mission) => mission.id === defaultMissionId)!;
}

export function getNextCampaignMissionDefinition(id: string) {
  const index = missionRegistry.findIndex((mission) => mission.id === id);
  return index >= 0 ? missionRegistry[index + 1] : undefined;
}

export function isCampaignMissionId(id: string) {
  return missionRegistry.some((mission) => mission.id === id);
}
